name: Workflow Run
on:
  workflow_run:
    workflows:
      - PR Open
      - Push
    types: completed
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
