name: Add Comment
on:
  workflow_run:
    workflows: PR Open
    types: completed
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pr.yml
          search_artifacts: true
          name: pull-request-number
          path: artifacts
      - name: Add comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue comment $(< artifacts/number.txt) --edit-last \
            --body "Your deploy preview can be found at https://setcookie-staging-${{ github.event.inputs.issue }}.fly.dev."
