name: Dependent jobs
on:
  push:
    branches: main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo job1
  job2:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - run: echo job2
  job3:
    runs-on: ubuntu-latest
    if: ${{ always() && github.event_name == 'push' }}
    needs: job2
    steps:
      - run: echo job3
