name: Matrix Outputs
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        thing: ["A", "B", "C"]
    steps:
      - name: Test
        id: test
				run: echo "wat=${{ matrix.thing }}" >> $GITHUB_OUTPUT

      - uses: cloudposse/github-action-matrix-outputs-write@0.3.0
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.thing }}
          outputs: |-
            blah: ${{ steps.test.outputs.wat }}

  ## Read matrix outputs
  read:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@0.3.0
        id: read
        with:
          matrix-step-name: build

    	- name: Output
				run: echo "${{ steps.read.outputs.result }}"
