name: PR Open
on:
  pull_request:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger comment workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run comment.yml
