name: Push
on: push
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo test
  two:
    needs: one
    runs-on: ubuntu-latest
    strategy:
      matrix:
        broken: ${{ needs.one.outputs.missing }}
    steps:
      - name: Output
        run: echo ${{ matrix.broken }}
